apiVersion: v1
kind: Service
metadata:
  name: training-nginx
spec:
  type: LoadBalancer
  selector:
    app: training-nginx
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-nginx
spec:
  selector:
    matchLabels:
      app: training-nginx
  template:
    metadata:
      labels:
        app: training-nginx
    spec:
      volumes:
      - name: volume-nginx-storage
        persistentVolumeClaim:
          claimName: claim-nginx-storage    
      containers:
      - name: training-nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: "http-server"
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: volume-nginx-storage