apiVersion: v1
kind: Service
metadata:
  name: training-api
spec:
  type: NodePort
  selector:
    app: training-api
  ports:
  - port: 8090
    targetPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: training-service
spec:
  type: LoadBalancer
  selector:
    app: training-service
  ports:
  - port: 8090
    targetPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-api
spec:
  selector:
    matchLabels:
      app: training-api
  template:
    metadata:
      labels:
        app: training-api
    spec:
      containers:
      - name: training-api
        image: borbassandor/training-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-service
spec:
  selector:
    matchLabels:
      app: training-service
  template:
    metadata:
      labels:
        app: training-service
    spec:
      containers:
      - name: training-service
        image: borbassandor/training-service
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8090

