apiVersion: v1
kind: Service
metadata:
  name: training-hello
spec:
  type: LoadBalancer
  selector:
    app: training-hello
  ports:
  - port: 8090
    targetPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-hello
spec:
  selector:
    matchLabels:
      app: training-hello
  template:
    metadata:
      labels:
        app: training-hello
    spec:
      containers:
      - name: training-hello
        image: borbassandor/training-hello:2.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8090

